import type { Invitation } from "@/domain/invitation";

export const mockInvitations: Invitation[] = [
  {
    id: "invitation-1",
    name: "Anna Jensen",
    email: "anna.jensen@example.com",
    locale: "da-DK",
    role: "clinician",
    status: "pending",
    createdAt: "2026-05-01T09:00:00.000Z",
  },
  {
    id: "invitation-2",
    name: "Mads Nielsen",
    email: "mads.nielsen@example.com",
    locale: "da-DK",
    role: "coordinator",
    status: "accepted",
    createdAt: "2026-05-02T11:30:00.000Z",
  },
  {
    id: "invitation-3",
    name: "Sarah Mitchell",
    email: "sarah.mitchell@example.com",
    locale: "en-US",
    role: "admin",
    status: "expired",
    createdAt: "2026-04-28T14:15:00.000Z",
  },
  {
    id: "invitation-4",
    name: "Jonas Petersen",
    email: "jonas.petersen@example.com",
    locale: "da-DK",
    role: "clinician",
    status: "revoked",
    createdAt: "2026-04-26T08:45:00.000Z",
  },
  {
    id: "invitation-5",
    name: "Emma Larsen",
    email: "emma.larsen@example.com",
    locale: "da-DK",
    role: "admin",
    status: "pending",
    createdAt: "2026-05-03T10:20:00.000Z",
  },
  {
    id: "invitation-6",
    name: "Oliver Hansen",
    email: "oliver.hansen@example.com",
    locale: "da-DK",
    role: "clinician",
    status: "accepted",
    createdAt: "2026-05-04T13:10:00.000Z",
  },
  {
    id: "invitation-7",
    name: "Emily Carter",
    email: "emily.carter@example.com",
    locale: "en-US",
    role: "coordinator",
    status: "pending",
    createdAt: "2026-05-05T07:55:00.000Z",
  },
  {
    id: "invitation-8",
    name: "Frederik Møller",
    email: "frederik.moller@example.com",
    locale: "da-DK",
    role: "clinician",
    status: "expired",
    createdAt: "2026-04-24T16:40:00.000Z",
  },
  {
    id: "invitation-9",
    name: "Laura Thompson",
    email: "laura.thompson@example.com",
    locale: "en-US",
    role: "admin",
    status: "accepted",
    createdAt: "2026-05-06T09:25:00.000Z",
  },
  {
    id: "invitation-10",
    name: "Sofie Andersen",
    email: "sofie.andersen@example.com",
    locale: "da-DK",
    role: "coordinator",
    status: "revoked",
    createdAt: "2026-04-22T12:00:00.000Z",
  },
  {
    id: "invitation-11",
    name: "William Brown",
    email: "william.brown@example.com",
    locale: "en-US",
    role: "clinician",
    status: "pending",
    createdAt: "2026-05-07T08:35:00.000Z",
  },
  {
    id: "invitation-12",
    name: "Nikolaj Sørensen",
    email: "nikolaj.sorensen@example.com",
    locale: "da-DK",
    role: "admin",
    status: "expired",
    createdAt: "2026-04-20T15:50:00.000Z",
  },
  {
    id: "invitation-13",
    name: "Charlotte Evans",
    email: "charlotte.evans@example.com",
    locale: "en-US",
    role: "coordinator",
    status: "accepted",
    createdAt: "2026-05-01T17:05:00.000Z",
  },
  {
    id: "invitation-14",
    name: "Magnus Lund",
    email: "magnus.lund@example.com",
    locale: "da-DK",
    role: "clinician",
    status: "pending",
    createdAt: "2026-05-02T06:45:00.000Z",
  },
  {
    id: "invitation-15",
    name: "Olivia Martin",
    email: "olivia.martin@example.com",
    locale: "en-US",
    role: "admin",
    status: "revoked",
    createdAt: "2026-04-18T11:15:00.000Z",
  },
  {
    id: "invitation-16",
    name: "Kasper Holm",
    email: "kasper.holm@example.com",
    locale: "da-DK",
    role: "coordinator",
    status: "accepted",
    createdAt: "2026-05-04T18:30:00.000Z",
  },
  {
    id: "invitation-17",
    name: "Isabella Wilson",
    email: "isabella.wilson@example.com",
    locale: "en-US",
    role: "clinician",
    status: "pending",
    createdAt: "2026-05-06T14:10:00.000Z",
  },
];
